name: qbi2019
channels:
  - satra
  - menpo
  - pluraldatum
  - glemaitre
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - pandas
  - notebook>=5.2.2
  - ipywidgets>=6.0.1
  - ipython>=7.5.0
  - pydot
  - h5py
  - scikit-image<=0.20
  - scikit-learn<=0.20
  - opencv3>=3.0
  - tensorflow
  - jupyter_contrib_nbextensions
  - graphviz
  - python-graphviz
  - seaborn
  - networkx
  - pip
  - pip:
    - keras==2.2.5
    - fsspec>=0.3.3x
    - plotly
    - pydot
    - distributed
    - psutil
    - kaggle
    - appmode
    - cloudpickle
    - autopep8
    - git+https://github.com/danielegrattarola/spektral
